name: CDN Deploy
# This workflow is disabled as its functionality is now handled by semantic-release.yml

on:
  workflow_dispatch:
    # Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to CDN
        run: |
          # Add your CDN deployment script here
          echo "Deploying to CDN..."
        env:
          CDN_API_KEY: ${{ secrets.CDN_API_KEY }}
          GITHUB_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
